MERGE SORT

In [5]:
import numpy as np

narr = np.array([[5, 2, 4], 
                [9, 6, 7], 
                [2, 3, 5], 
                [1, 12, 8]])

sorted_narr= np.sort(narr.flatten(), kind='mergesort')  # Simultaneous sorting of rows and columns with QuickSort 

sorted_narr = sorted_narr.reshape(narr.shape)# Reconstruction of the sorted array in the original matrix form

print(sorted_narr)

[[ 1  2  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 12]]


In [8]:
narr = np.array([[5, 2, 4], 
                [9, 6, 7], 
                [2, 3, 5], 
                [1, 12, 8]])
sorted_narr = np.sort(narr , axis=0, kind='mergesort') #Sorted by rows

print(sorted_narr)

[[ 1  2  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 9 12  8]]


In [7]:
narr = np.array([[5, 2, 4], 
                [9, 6, 7], 
                [2, 3, 5], 
                [1, 12, 8]])
sorted_narr = np.sort(narr , axis=0, kind='mergesort') #Sorted by rows

print(sorted_narr)

[[ 1  2  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 9 12  8]]
