QUICK SORT

In [1]:
import numpy as np

In [46]:
narr = np.array([[5, 2, 4], 
                [9, 6, 7], 
                [2, 3, 5], 
                [1, 12, 8]])
sorted_narr = np.sort(narr , axis=0, kind='quicksort') #Sorted by rows

print(sorted_narr)

[[ 1  2  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 9 12  8]]


In [41]:
narr = np.array([[5, 2, 4], 
                [9, 6, 7], 
                [2, 3, 5], 
                [1, 12, 8]])
sorted_narr = np.sort(narr , axis=1, kind='quicksort') #Sorted by columns


print(sorted_narr)

[[ 2  4  5]
 [ 6  7  9]
 [ 2  3  5]
 [ 1  8 12]]


In [48]:


narr = np.array([[5, 2, 4], 
                [9, 6, 7], 
                [2, 3, 5], 
                [1, 12, 8]])

sorted_narr= np.sort(narr.flatten(), kind='quicksort')  # Simultaneous sorting of rows and columns with QuickSort 

sorted_narr = sorted_narr.reshape(narr.shape)# Reconstruction of the sorted array in the original matrix form

print(sorted_narr)

[[ 1  2  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 12]]


toye code bala man aval az axis= none estefade kardam ke betonam hamzam ham be sorat satri va ham be sorat sotoni sort konam vali 
didam ke matrix tabdil mishe be yek array yek bodi baraye hamin az func flatten va reshape estefade kardam ta matrix bad az sort shodan reshape beshe.